export const ADDINGREDIENT='ADDINGREDIENTS'
export const REMOVEINGREDIENT='REMOVEINGREDIENTS'
export const INITIALIZE='INITIALIZE'
export const RESET_PRICE='RESET_PRICE'
export const BUILDING='BUILDING'
export const RESET_BUILDING='RESET_BUILDING';

export const PRICE='PRICE'

export const SIGNUP_SUCCESS='SIGNUP_SUCCESS';
export const SIGNUP_FAIL='SIGNUP_FAIL';
export const SIGNUP_START='SIGNUP_START';
export const LOGOUT='LOGOUT';
export const CHECK_AUTH='CHECK_AUTH';